### ISSUE TITLE
Update project components page to include new project repos

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/project_electron#89]
## Is your feature request related to a problem? Please describe.
We have multiple new project components with their own GitHub repositories that should be discoverable through the Project Electron website.

## Describe the solution you'd like
Update Project Components page to include discovery infrastructure that is not currently on the website. Repos include:
- Cartographer
- pisces
- request broker
- zorya
- asterism
- nebula

**Comment by helrond** [comment]
One thing I've tried to do, but is probably done pretty inconsistently, is to use [repository topics](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) to tag Project Electron repos. Could help out with discovery as well because you could point to a single URL rather than adding another one to a list.

**Comment by HaSistrunk** [comment]
Oh, interesting. Yeah, as this list grows that that may be a better approach. I'll look at that more closely.
